### ISSUE TITLE
jekyll build报错

### ISSUE THREAD

**Issue by zhangwei900808** [minixalpha/minixalpha.github.io#7]
我在项目下准备生成归档文件，但是提示报错，请问下如何解决：

```
➜  zhangwei900808.github.io git:(master) ✗ jekyll --version
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/plugin_manager.rb:34:in `require_from_bundler'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by 54lxb** [comment]
不好意思，我不知道这个东西，使用GitHub都在自己自学的。遇到问题就百度？很抱歉，不能帮到你。

**Comment by zhangwei900808** [comment]
那你是如何生成归档文件的啊，我参考下
